config/routes.rb
Chess::Application.routes.draw do

  devise_for :users
  root :to => "home#index"
  resources :games do
    member do
      get :export
    end
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = current_user.games
  end
  
  def show
  end
  
  def new
    @game = Game.new
  end
  
  def edit
    @game = Game.find(params[:id])
  end
  
  def create
    begin
      Game.transaction do
        current_user.games.create params[:game].permit(:pgn)
      end
    end
    redirect_to games_path
  end
  
  def update
    @game = Game.find(params[:id])
    @game.update_attributes(params[:game].permit(:pgn))
    redirect_to games_path
  end
  
  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path
  end

  def export
    @game = Game.find(params[:id])
    send_data @game.pgn
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_form.html.erb
<%= form.label :pgn %>
<%= form.text_field :pgn %>

app/views/games/edit.html.erb
<%= form_for @game, url: {action: "update"} do |f| %>

<%= render :partial => 'games/form', :object => f %>
  <p>
    <%= submit_tag "Update" %>
  </p>
<% end %>

app/views/games/index.html.erb
<%= link_to 'New Game', new_game_path %>
<%= content_tag :ul do %>
	<% @games.each do |game| %>
		<%= content_tag :li do %>
			<%= game.pgn %>
			<%= link_to 'edit', edit_game_path(game) %>
			<%= link_to 'delete', game_path(game), :confirm => 'Are you sure?', :method => :delete %>
			<%= link_to 'export', export_game_path(game) %>
		<% end %>
	<% end %>
<% end %>

app/views/games/new.html.erb
<%= form_for @game do |form| %>
	<%= render :partial => 'games/form', :locals => {:form => form} %>
	<%= form.submit 'Submit' %>
<% end %>

app/views/games/show.html.erb
<canvas id='board' width='730' height='730'></canvas>

<script type='text/javascript'>
var scale = 80;
var canvas = document.getElementById('board');
canvas.addEventListener("mousedown", onClick, false);
var ctx = canvas.getContext('2d');

function King(color, file, rank) {
  this.color = color;
  this.file = file;
  this.rank = rank;
}
King.prototype.getUnicodeCharacter = function() {
  return 9812+6*this.color;
};

function Queen(color, file, rank) {
  this.color = color;
  this.file = file;
  this.rank = rank;
}
Queen.prototype.getUnicodeCharacter = function() {
  return 9813+6*this.color;
};

function Rook(color, file, rank) {
  this.color = color;
  this.file = file;
  this.rank = rank;
}
Rook.prototype.getUnicodeCharacter = function() {
  return 9814+6*this.color;
};

function Bishop(color, file, rank) {
  this.color = color;
  this.file = file;
  this.rank = rank;
}
Bishop.prototype.getUnicodeCharacter = function() {
  return 9815+6*this.color;
};

function Knight(color, file, rank) {
  this.color = color;
  this.file = file;
  this.rank = rank;
}
Knight.prototype.getUnicodeCharacter = function() {
  return 9816+6*this.color;
};

function Pawn(color, file, rank) {
  this.color = color;
  this.file = file;
  this.rank = rank;
}
Pawn.prototype.getUnicodeCharacter = function() {
  return 9817+6*this.color;
};

function getCharacterPosition(file, rank) {
  file = file.toLowerCase().charCodeAt(0)-97
  return [file*(scale+1)+(scale*1.15), (scale*8-scale*.125)-(rank-1)*(scale+1)]
}

function getSquarePosition(file, rank) {
  return [file*(scale+1), ((scale+1)*8)-rank*(scale+1)]  
}

function onClick(event) {
  var x = event.clientX-document.documentElement.scrollLeft-canvas.offsetLeft;
  var y = event.clientY-document.documentElement.scrollTop-canvas.offsetTop;
  
  if(x < (scale+1) || y > (scale+1)*8){
    return;
  }
  clickOnBoard(Math.floor((x-(scale+1))/(scale+1))+1, Math.floor(9-y/(scale+1)));
}

function clickOnBoard(file, rank) {
  var position = getSquarePosition(file, rank);
  ctx.strokeStyle = '#ffff00';
  ctx.lineWidth = 3;
  
  ctx.beginPath();
  ctx.moveTo(position[0]+3, position[1]+3);
  ctx.lineTo(position[0]+scale-1, position[1]+3);
  ctx.lineTo(position[0]+scale-1, position[1]+scale-1);
  ctx.lineTo(position[0]+3, position[1]+scale-1);
  ctx.lineTo(position[0]+3, position[1]+3);
  ctx.stroke();
}

ctx.fillStyle = '#99ddff';
for(var i = 1; i <= 8; i += 2) {
  for(var j = 0; j < 8; j += 2) {
    ctx.fillRect((i+1)*(scale+1), j*(scale+1), scale, scale);
    ctx.fillRect(i*(scale+1), (j+1)*(scale+1), scale, scale);
  }
}

ctx.fillStyle = '#fcfcfc';
for(var i = 1; i <= 8; i += 2) {
  for(var j = 0; j < 8; j += 2) {
    ctx.fillRect(i*(scale+1), j*(scale+1), scale, scale);
    ctx.fillRect((i+1)*(scale+1), (j+1)*(scale+1), scale, scale);
  }
}

ctx.strokeStyle = '#000000';
for(var i = 1; i <= 9; i++) {
  ctx.beginPath();
  ctx.moveTo(i*(scale+1), 0);
  ctx.lineTo(i*(scale+1), 8*(scale+1));
  ctx.stroke();
  
  ctx.beginPath();
  ctx.moveTo((scale+1), (i-1)*(scale+1));
  ctx.lineTo(9*(scale+1), (i-1)*(scale+1));
  ctx.stroke();
}

ctx.fillStyle = '#000000';
ctx.font = scale*0.75+"px sans-serif";

var whitePieces = new Array();
whitePieces[0] = new King(0, 'e', 1);
whitePieces[1] = new Queen(0, 'd', 1);
whitePieces[2] = new Rook(0, 'a', 1);
whitePieces[3] = new Rook(0, 'h', 1);
whitePieces[4] = new Bishop(0, 'c', 1);
whitePieces[5] = new Bishop(0, 'f', 1);
whitePieces[6] = new Knight(0, 'b', 1);
whitePieces[7] = new Knight(0, 'g', 1);
for(var i = 1; i <= 8; i++) {
  whitePieces[i+7] = new Pawn(0, String.fromCharCode(i+96), 2);
}
for(var i = 0; i < whitePieces.length; i++) {
  ctx.fillText(
    String.fromCharCode(whitePieces[i].getUnicodeCharacter()),
    getCharacterPosition(whitePieces[i].file, whitePieces[i].rank)[0],
    getCharacterPosition(whitePieces[i].file, whitePieces[i].rank)[1]
  );
}

var blackPieces = new Array();
blackPieces[0] = new King(1, 'e', 8);
blackPieces[1] = new Queen(1, 'd', 8);
blackPieces[2] = new Rook(1, 'a', 8);
blackPieces[3] = new Rook(1, 'h', 8);
blackPieces[4] = new Bishop(1, 'c', 8);
blackPieces[5] = new Bishop(1, 'f', 8);
blackPieces[6] = new Knight(1, 'b', 8);
blackPieces[7] = new Knight(1, 'g', 8);
for(var i = 1; i <= 8; i++) {
  blackPieces[i+7] = new Pawn(1, String.fromCharCode(i+96), 7);
}
for(var i = 0; i < blackPieces.length; i++) {
  ctx.fillText(
    String.fromCharCode(blackPieces[i].getUnicodeCharacter()),
    getCharacterPosition(blackPieces[i].file, blackPieces[i].rank)[0],
    getCharacterPosition(blackPieces[i].file, blackPieces[i].rank)[1]
  );
}
</script>

app/views/home/index.html.erb
WELCOME TO THE CHESS APP 9,000,000
<br />
<% if user_signed_in? %>
	<%= link_to 'Games', games_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chess</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:error] %>
	  <p class='error'><%=h flash[:error] %></p>
	<% end %>
	<% if flash[:notice] %>
	  <p class='notice'><%=h flash[:notice] %></p>
	<% end %>
	<% if user_signed_in? %>
		<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	<% else %>
		<%= link_to "Sign in", new_user_session_path %> or <%= link_to "Regiser", new_registration_path(:user) %>
	<% end %>
	<br/>
	<%= yield %>
</body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>